In [1]:
import pandas as pd

In [2]:
data= {"Tid": [1,2,3,4,5,6,7,8,9,10],
      "Refund": ["Yes", "No", "No", "Yes", "No", "No", "Yes", "No", "No", "No"],
       "Marital Status": [
        "Single", "Married", "Single", "Married", "Divorced",
        "Married", "Divorced", "Single", "Married", "Single"
    ],
        "Taxable Income": [
        "125K", "100K", "70K", "120K", "95K",
        "60K", "220K", "85K", "75K", "90K"
    ],
    "Cheat": ["No", "No", "No", "No", "Yes", "No", "No", "Yes", "No", "Yes"]
      }
df = pd.DataFrame(data)
df

   Tid Refund Marital Status Taxable Income Cheat
0    1    Yes         Single           125K    No
1    2     No        Married           100K    No
2    3     No         Single            70K    No
3    4    Yes        Married           120K    No
4    5     No       Divorced            95K   Yes
5    6     No        Married            60K    No
6    7    Yes       Divorced           220K    No
7    8     No         Single            85K   Yes
8    9     No        Married            75K    No
9   10     No         Single            90K   Yes

In [3]:
df.iloc[[0,4,7,8]]

   Tid Refund Marital Status Taxable Income Cheat
0    1    Yes         Single           125K    No
4    5     No       Divorced            95K   Yes
7    8     No         Single            85K   Yes
8    9     No        Married            75K    No

In [4]:
df.loc[[0,4,7,8]]

   Tid Refund Marital Status Taxable Income Cheat
0    1    Yes         Single           125K    No
4    5     No       Divorced            95K   Yes
7    8     No         Single            85K   Yes
8    9     No        Married            75K    No

In [5]:
df.loc[3: 7]

   Tid Refund Marital Status Taxable Income Cheat
3    4    Yes        Married           120K    No
4    5     No       Divorced            95K   Yes
5    6     No        Married            60K    No
6    7    Yes       Divorced           220K    No
7    8     No         Single            85K   Yes

In [6]:
df.loc[4:8, ["Marital Status", "Taxable Income", "Cheat"]]

  Marital Status Taxable Income Cheat
4       Divorced            95K   Yes
5        Married            60K    No
6       Divorced           220K    No
7         Single            85K   Yes
8        Married            75K    No

In [7]:
df.iloc[4:9,2:5]

  Marital Status Taxable Income Cheat
4       Divorced            95K   Yes
5        Married            60K    No
6       Divorced           220K    No
7         Single            85K   Yes
8        Married            75K    No

In [8]:
df.iloc[:, 1:4]

  Refund Marital Status Taxable Income
0    Yes         Single           125K
1     No        Married           100K
2     No         Single            70K
3    Yes        Married           120K
4     No       Divorced            95K
5     No        Married            60K
6    Yes       Divorced           220K
7     No         Single            85K
8     No        Married            75K
9     No         Single            90K

In [9]:
df_iris=pd.read_csv(r"C:\Users\vijay\Desktop\UCS420\Iris.csv")
df_iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [10]:
##question5

In [11]:
df_iris=df.drop(index=3)
df_iris=df.drop(df.columns[2],axis=1)
df_iris

   Tid Refund Taxable Income Cheat
0    1    Yes           125K    No
1    2     No           100K    No
2    3     No            70K    No
3    4    Yes           120K    No
4    5     No            95K   Yes
5    6     No            60K    No
6    7    Yes           220K    No
7    8     No            85K   Yes
8    9     No            75K    No
9   10     No            90K   Yes

In [12]:
##question 6

In [13]:
df = pd.read_csv("employees.csv")

print("Original Dataset:")
print(df)

Original Dataset:
   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
0          101    Alice         HR   29   50000                    4
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating
0    3/15/2020  Female   5000     4.5
1    7/19/2017    Male   7000     4.0
2     6/1/2013    Male   6000     3.8
3    2/10/2021  Female   4500     4.7
4   11/25/2010    Male   5000     3.5

In [14]:
df.head()

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,3/15/2020,Female,5000,4.5
1,102,Bob,IT,34,70000,8,7/19/2017,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,6/1/2013,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2/10/2021,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,11/25/2010,Male,5000,3.5

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      object
 2   Department           5 non-null      object
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      object
 7   Gender               5 non-null      object
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: float64(1), int64(5), object(4)
memory usage: 532.0+ bytes

In [16]:
df.shape

(5, 10)

In [17]:
df.describe()

,Employee_ID,Age,Salary,Years_of_Experience,Bonus,Rating
count,5.000000,5.000000,5.00000,5.000000,5.0,5.000000
mean,103.000000,34.000000,60000.00000,7.400000,5500.0,4.100000
std,1.581139,5.612486,7905.69415,3.847077,1000.0,0.494975
min,101.000000,28.000000,50000.00000,3.000000,4500.0,3.500000
25%,102.000000,29.000000,55000.00000,4.000000,5000.0,3.800000
50%,103.000000,34.000000,60000.00000,8.000000,5000.0,4.000000
75%,104.000000,38.000000,65000.00000,10.000000,6000.0,4.500000
max,105.000000,41.000000,70000.00000,12.000000,7000.0,4.700000

In [18]:
df.tail(3)

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
2,103,Charlie,IT,41,65000,10,6/1/2013,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2/10/2021,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,11/25/2010,Male,5000,3.5

In [19]:
average_salary = df["Salary"].mean()
average_salary

np.float64(60000.0)

In [20]:
total_bonus = df["Bonus"].sum()
total_bonus

np.int64(27500)

In [21]:
youngest_age = df["Age"].min()
youngest_age

28

In [22]:
highest_rating = df["Rating"].max()
highest_rating

4.7

In [25]:
sorted_df = df.sort_values(by="Salary", ascending=False)
sorted_df

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
1,102,Bob,IT,34,70000,8,7/19/2017,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,6/1/2013,Male,6000,3.8
4,105,Edward,Sales,38,60000,12,11/25/2010,Male,5000,3.5
3,104,Diana,Marketing,28,55000,3,2/10/2021,Female,4500,4.7
0,101,Alice,HR,29,50000,4,3/15/2020,Female,5000,4.5

In [26]:
def performance_category(rating):
    if rating >= 4.5:
        return "Excellent"
    elif rating >= 4.0:
        return "Good"
    else:
        return "Average"

df["Performance_Category"] = df["Rating"].apply(performance_category)
df

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
0,101,Alice,HR,29,50000,4,3/15/2020,Female,5000,4.5,Excellent
1,102,Bob,IT,34,70000,8,7/19/2017,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,6/1/2013,Male,6000,3.8,Average
3,104,Diana,Marketing,28,55000,3,2/10/2021,Female,4500,4.7,Excellent
4,105,Edward,Sales,38,60000,12,11/25/2010,Male,5000,3.5,Average

In [27]:
print(df.isnull().sum())

Employee_ID             0
Name                    0
Department              0
Age                     0
Salary                  0
Years_of_Experience     0
Joining_Date            0
Gender                  0
Bonus                   0
Rating                  0
Performance_Category    0
dtype: int64

In [28]:
df = df.rename(columns={"Employee_ID": "ID"})
df

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
0,101,Alice,HR,29,50000,4,3/15/2020,Female,5000,4.5,Excellent
1,102,Bob,IT,34,70000,8,7/19/2017,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,6/1/2013,Male,6000,3.8,Average
3,104,Diana,Marketing,28,55000,3,2/10/2021,Female,4500,4.7,Excellent
4,105,Edward,Sales,38,60000,12,11/25/2010,Male,5000,3.5,Average

In [29]:
it_employees = df[df["Department"] == "IT"]
it_employees

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
1,102,Bob,IT,34,70000,8,7/19/2017,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,6/1/2013,Male,6000,3.8,Average

In [30]:
df["Tax"] = df["Salary"] * 0.10
df

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category,Tax
0,101,Alice,HR,29,50000,4,3/15/2020,Female,5000,4.5,Excellent,5000.0
1,102,Bob,IT,34,70000,8,7/19/2017,Male,7000,4.0,Good,7000.0
2,103,Charlie,IT,41,65000,10,6/1/2013,Male,6000,3.8,Average,6500.0
3,104,Diana,Marketing,28,55000,3,2/10/2021,Female,4500,4.7,Excellent,5500.0
4,105,Edward,Sales,38,60000,12,11/25/2010,Male,5000,3.5,Average,6000.0

In [31]:
df.to_csv("employees_modified.csv", index=False)

In [32]:
df

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category,Tax
0,101,Alice,HR,29,50000,4,3/15/2020,Female,5000,4.5,Excellent,5000.0
1,102,Bob,IT,34,70000,8,7/19/2017,Male,7000,4.0,Good,7000.0
2,103,Charlie,IT,41,65000,10,6/1/2013,Male,6000,3.8,Average,6500.0
3,104,Diana,Marketing,28,55000,3,2/10/2021,Female,4500,4.7,Excellent,5500.0
4,105,Edward,Sales,38,60000,12,11/25/2010,Male,5000,3.5,Average,6000.0